import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Bell, ShieldAlert, AlertTriangle, Info, Package, MapPin, Clock, ArrowRight, ChevronRight, RefreshCw, CheckCircle2 } from 'lucide-react'
import api from '../services/api.js'

const typeTabs = [
  { key: 'all', label: 'All Alerts' },
  { key: 'critical', label: 'Critical' },
  { key: 'warning', label: 'Low Stock & Warnings' },
  { key: 'info', label: 'Info' },
]

export default function Alerts() {
  const navigate = useNavigate()
  const [alertsList, setAlertsList] = useState([])
  const [loading, setLoading] = useState(true)
  const [activeTab, setActiveTab] = useState('all')
  const [refreshing, setRefreshing] = useState(false)

  const loadAlerts = async () => {
    try {
      const res = await api.alerts.getAll()
      if (res.success && res.data) {
        setAlertsList(res.data)
      }
    } catch (err) {
      console.error('Failed to load alerts:', err)
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }

  useEffect(() => {
    loadAlerts()
  }, [])

  const handleResolve = async (id) => {
    try {
      await api.alerts.resolve(id)
      loadAlerts()
    } catch (err) {
      console.error('Failed to resolve alert:', err)
    }
  }

  const filtered = activeTab === 'all'
    ? alertsList
    : alertsList.filter(a => a.type === activeTab || a.severity?.toLowerCase() === activeTab)

  const counts = {
    all: alertsList.length,
    critical: alertsList.filter(a => a.type === 'critical' || a.severity === 'CRITICAL').length,
    warning: alertsList.filter(a => a.type === 'warning' || a.severity === 'WARNING').length,
    info: alertsList.filter(a => a.type === 'info' || a.severity === 'INFO').length,
  }

  return (
    <div>
      <div className="page-header">
        <div className="page-header-row">
          <div>
            <h1 className="page-header-title">Operational Alert Center</h1>
            <p className="page-header-subtitle">
              {alertsList.length} active system alerts generated by real-time safety stock and reorder rules
            </p>
          </div>
          <div className="page-header-actions">
            <button className="btn btn-secondary btn-sm" onClick={() => { setRefreshing(true); loadAlerts(); }} disabled={refreshing}>
              <RefreshCw size={14} className={refreshing ? 'spin' : ''} />
              <span>Refresh</span>
            </button>
          </div>
        </div>
      </div>

      <div className="alert-tabs">
        {typeTabs.map(tab => (
          <button
            key={tab.key}
            className={`alert-tab${activeTab === tab.key ? ' active' : ''}`}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
            <span className="alert-tab-count">{counts[tab.key] || 0}</span>
          </button>
        ))}
      </div>

      <div className="card">
        <div className="card-body" style={{ padding: 0 }}>
          {loading ? (
            <div style={{ padding: '48px', textAlign: 'center', color: 'var(--text-secondary)' }}>
              Checking active warehouse alerts...
            </div>
          ) : filtered.length === 0 ? (
            <div style={{ padding: '48px', textAlign: 'center', color: 'var(--text-tertiary)' }}>
              <CheckCircle2 size={32} style={{ color: 'var(--success-500)', margin: '0 auto 12px' }} />
              <div>No alerts matching this filter. All inventory thresholds healthy!</div>
            </div>
          ) : (
            filtered.map(alert => (
              <div key={alert.id} className="alert-item">
                <div className={`alert-icon ${alert.type || alert.severity?.toLowerCase()}`}>
                  {(alert.type === 'critical' || alert.severity === 'CRITICAL') && <ShieldAlert size={16} />}
                  {(alert.type === 'warning' || alert.severity === 'WARNING') && <AlertTriangle size={16} />}
                  {(alert.type === 'info' || alert.severity === 'INFO') && <Info size={16} />}
                </div>
                <div className="alert-content">
                  <div className="alert-title">{alert.title}</div>
                  <div className="alert-desc">{alert.desc || alert.message}</div>
                  <div className="alert-meta">
                    {alert.location && (
                      <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <MapPin size={12} /> {alert.location}
                      </span>
                    )}
                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                      <Clock size={12} /> {alert.time ? new Date(alert.time).toLocaleDateString() : 'Active'}
                    </span>
                  </div>
                  <div className="alert-actions">
                    {alert.action && (
                      <button className="btn btn-sm btn-primary" onClick={() => navigate('/receipts')}>
                        {alert.action}
                      </button>
                    )}
                    {alert.productId && (
                      <button className="btn btn-sm btn-ghost" onClick={() => navigate(`/products/${alert.productId}`)}>
                        View Product Stock <ChevronRight size={12} />
                      </button>
                    )}
                    <button className="btn btn-sm btn-secondary" onClick={() => handleResolve(alert.id)}>
                      Dismiss Alert
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}
